# Site settings
title: Welcome to my portfolio
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/abellakr.github.io" # the subpath of your site, e.g. /blog/
url: "http://abellakr.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown

future: true
encoding: UTC-6
